version: '3.1'
services:
  web:
    image: jackson147/wedding-site:latest
    build: ./wedding-site
    ports:
      - '80:80'
      - '443:443'
    secrets:
      - server.ca
      - server.crt
      - server.key
  api:
    image: jackson147/wedding-api:latest
    build: ./wedding-api
    ports:
      - '8080:3001'
    secrets:
      - server.ca
      - server.crt
      - server.key
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
    - ./db:/data/db

secrets:
  server.ca:
    external: true
  server.crt:
    external: true
  server.key:
    external: true
