version: '3.1'
services:
  web:
    build: 
      context: ./wedding-site
      dockerfile: Dockerfile.dev
    volumes:
       - ./wedding-site:/code
    ports:
      - '80:4200'
    links:
      - api
    depends_on:
    - 'api'
  api:
    build: 
      context: ./wedding-api
      dockerfile: Dockerfile.dev
    volumes:
       - ./wedding-api:/code
    ports:
      - '8080:3001'
  mongo:
    image: mongo
    ports:
      - '27017:27017'
