version: '3.1'
services:
  web:
    image: jackson147/wedding-site:latest
    build: ./wedding-site
    ports:
      - '80:80'
  api:
    image: jackson147/wedding-api:latest
    build: ./wedding-api
    ports:
      - '8080:3001'
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./db:/data/db
      - ./backups:/backups
